# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f969cec504c76adf4cc49d3d82f08833ad52d0f931e59a7eb8dc2dedf4771f29a819422ba6b9435cc83373f5e63fdeb5c6d486600d6ce0333621a8a91a83d8d8

test:
  secret_key_base: 0e1c0f373dee310c7f7d8cf21dd8f2fa08ec7d6f91d80311cde948a821daa1841b237fc37bb7bcd8f3db0e0aaecd2f0996277176b0d6106d6e4db14e8c865d8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
